Create model darunphop
cpe24fundb/412-Shop pull request #20
Opened 2017-10-19 16:39 UTC by Darunphop

#17

2017-10-20 13:08 UTC, chawasit commented
notification ไม่มี many to many หา product หรอ?

2017-10-20 15:38 UTC, Darunphop commented
เห็นอิกบอกว่าทำเฉพาะ entity หลัก กับ one to one, one to many ไปก่อน ก็เลยยังไม่ได้ทำ many to many

2017-10-23 12:22 UTC, chawasit requested changes

2017-10-23 12:22 UTC, chawasit commented on app/Models/Notification.php
> +        return $this->belongsToMany('App/Models/Product');
hasMany ?

2017-10-23 12:22 UTC, chawasit commented on app/Models/Product.php
> +        return $this->belongsToMany('App\Models\Notification');
ใส่ตาราง subscribe  ด้วย

2017-10-25 08:09 UTC, chawasit approved these changes

2017-10-25 08:09 UTC, merged