Create model boom
cpe24fundb/412-Shop pull request #22
Opened 2017-10-19 17:45 UTC by apboomap

#17

2017-10-20 13:27 UTC, chawasit requested changes

2017-10-20 13:27 UTC, chawasit commented on app/Models/Stock.php
> +        return $this->belongsToMany('App\Models\User');
stock มี user คนเดียวเป็นคนกรอกใช่ไหม? จะใช้ belongsTo นะ

2017-10-20 13:27 UTC, chawasit commented on app/Models/Stock.php
> +        return $this->belongsToMany('App\Models\Product');
ตรงนี้คือ stock item ป่าว

2017-10-20 13:27 UTC, chawasit commented on app/Models/User.php
> +        return $this->belongsToMany('App\Stock');
hasMany ?

2017-10-20 13:27 UTC, chawasit commented on app/Models/User.php
>      use Authenticatable, Authorizable;
use น่าจะอยู่บนสุดใน class นะ

2017-10-21 17:44 UTC, apboomap commented on app/Models/Stock.php
> +        return $this->belongsToMany('App\Models\Product');
ใช่

2017-10-21 17:49 UTC, apboomap commented on app/Models/Stock.php
> +        return $this->belongsToMany('App\Models\User');
ใช่อันนี้ลืมดูใน ตาราง ERR มันใส่ผิดลืมเเก้

2017-10-23 12:26 UTC, chawasit requested changes

2017-10-23 12:26 UTC, chawasit commented on app/Models/Stock.php
> +        return $this->belongsToMany('App\Models\StockItems');
hasMany items ?

2017-10-24 06:43 UTC, merged